# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bernard Munslow
tagline:          'Full stack web and developer and Drupal enthusiast'
description:      'Bernard Munslow is a web developer with a passion for coding, biking and cookies. Also known as <a href="https://twitter.com/b_munslow" target="_blank">@b_munslow</a> in Twitter. <a href="/about">Learn more</a>.'
url:              http://www.bmunslow.com
baseurl:          /

author:
  name:           'Bernard Munslow'
  url:            https://twitter.com/b_munslow

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bmunslow

linkedin:
  profile:	https://es.linkedin.com/in/bernardmunslow/en
