# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bernard Munslow
tagline:          'Full stack web developer and Drupal enthusiast'
description:      'Web developer with a passion for coding, biking and cookies. Also known as <a href="https://www.drupal.org/u/bmunslow" target="_blank">@bmunslow</a> in Drupal.org <a href="/about">Learn more</a>.'
url:              https://bmunslow.com
baseurl:          /

author:
  name:           'Bernard Munslow'
  url:            https://www.drupal.org/u/bmunslow

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bmunslow

linkedin:
  profile:	https://es.linkedin.com/in/bernardmunslow/en
